### ISSUE TITLE
Who to contact for security issues

### ISSUE THREAD

**Issue by zidingz** [fecshop/yii2_fecshop#100]
Hey there!

I belong to an open source security research community, and a member (@sudheendra17) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by fancyecommerce** [comment]
https://github.com/fecshop/yii2_fecshop/blob/master/SECURITY.md

security.md file has created. thank you .

**Comment by JamieSlome** [comment]
@fancyecommerce - please see the report here:

https://huntr.dev/bounties/0faf3ab0-a011-4939-b6ee-da9118da60f7/

It is private and only accessible to maintainers with repository write permissions 👍

**Comment by fancyecommerce** [comment]
@zidingz  mail to fecify@126.com , thanks

**Comment by psmoros** [comment]
Will do @fancyecommerce  :) Thank you!
