### ISSUE TITLE
官网打不开了，数据库连接报错？

### ISSUE THREAD

**Issue by helloxz** [fecshop/yii2_fecshop#101]
官网[https://www.fecmall.com/](https://www.fecmall.com/)挂了？

> Database Exception – yii\db\Exception
SQLSTATE[HY000] [2002] Connection refused
↵
Caused by: PDOException
SQLSTATE[HY000] [2002] Connection refused

**Comment by fancyecommerce** [comment]
磁盘满了，已经处理了
