### ISSUE TITLE
这是不维护了么

### ISSUE THREAD

**Issue by guiyumin** [fecshop/yii2_fecshop#104]
### What steps will reproduce the problem?

2年没更新了

### Additional info

| Q                | A
| ---------------- | ---
| Fecshop version  | 1.1.3.?
| PHP version      | 
| Operating system |

**Comment by fancyecommerce** [comment]
fecmall是2015年开始的项目，项目历程：https://www.fecmall.com/site/timeline

做为一款面向程序员的电商商城，遵循BSD-3-Clause开源协议，主要是程序员拿到做二次开发，bug基本都处理了，也够用了，fecmall项目维护了7年多。

做开源比较艰难，没有收入，只能一个人写，而一个人的力量很难完成一个优秀的作品，而团队合作需要适当的收入，没有收入的项目是很难聚集团队的。

我们目前的重心是开发fecify，独立站saas系统，纯商业系统，付费授权，团队项目，独立站无限开的saas版本，有兴趣可以了解一下fecify跨境saas独立站
