### ISSUE TITLE
提示 'Method fecshop\services\Store::bootstrap() does not exist'

### ISSUE THREAD

**Issue by huanggd** [fecshop/yii2_fecshop#17]
安装了v1.1.3.3版本，在没有配置好域名情况下执行时的报错问题：提示 'Method fecshop\services\Store::bootstrap() does not exist'。需要在vendor\fancyecommerce\fecshop\services\Store.php里添加以下代码才能正常报错：
```
public function bootstrap($app)
{
    $this->actionBootstrap($app);
}
```

**Comment by lichunqiang** [comment]
错误栈贴一下

**Comment by fancyecommerce** [comment]
严格按照文档安装

https://github.com/fecshop/yii2_fecshop/blob/master/services/Store.php
这个函数是存在的，我估计你安装没有按照步骤来。
