### ISSUE TITLE
CMS静态块添加时，提示MongoId类不存在，好多地方都有这个问题，怎么解决，谢谢回答。

### ISSUE THREAD

**Issue by hanxm** [fecshop/yii2_fecshop#18]
### Additional info

| Q                | A
| ---------------- | ---
| Fecshop version  | 1.1.3.?
| PHP version      | 
| Operating system |

**Comment by fancyecommerce** [comment]
请安装 php-mongodb 扩展。

**Comment by hanxm** [comment]
谢谢老师，插件已经安装了，并且数据库连接成功，查询数据也都OK，就是在添加的时候提醒没有MongoId
php-mongodb is already the newest version (1.1.5-1~build1).
