### ISSUE TITLE
安装不上。

### ISSUE THREAD

**Issue by dafa168** [fecshop/yii2_fecshop#19]
### What steps will reproduce the problem?
mongodb  is not installed ??
### Additional info

| Q                | A
| ---------------- | ---
| Fecshop version  | 1.1.3.?
| PHP version      | 
| Operating system |

**Comment by lichunqiang** [comment]
提供的信息太少了吧？mongo没装就装上呀，一步步按照文档来

**Comment by fancyecommerce** [comment]
使劲装
