### ISSUE TITLE
七层命名空间看的我累了

### ISSUE THREAD

**Issue by wuyuxifeng** [fecshop/yii2_fecshop#22]
/app/apphtml5/modules/Catalog/block/category/index
简单，少点也许更好理解

**Comment by fancyecommerce** [comment]
来，你给我个完整的简单的方案，还要满足我的要求。

**Comment by wuyuxifeng** [comment]
多域名绑定到模块是么

**Comment by fancyecommerce** [comment]
不明白你说是什么意思，你先安装fecshop，了解下吧。

fecshop是精心设计的，2015年开始的开源项目一直到现在，当然，不足也是存在的，你认为不足，请给予你认为满意的方案。
