### ISSUE TITLE
整合到微信公众号

### ISSUE THREAD

**Issue by taurenshaman** [fecshop/yii2_fecshop#23]
现在流行新零售，先不说实体门店和网店，准备与微信公众号进行整合吗？  

0. 君不见做微信整合的收费都是超级黑吗？我感觉他们都是在给SaaS抹黑。fecshop完善了，搞个SaaS的版本，干掉它们  
1. 通过配置替换掉公众号自带的微信小店   
2. 会员与微信的卡包进行深度整合  
3. 在1和2的基础上提供营销方面的多种玩法。其实这才是最重要的，毕竟单纯的整合没太大意义，必须用到、用好微信的社交特性才值得这些付出

**Comment by fancyecommerce** [comment]
一直做跨境电商B2C，和微信公众号整合的微商，需求不是很了解，没做过那一块。

如果您有想法，在www.fecshop.com发帖吧（大家都在www.fecshop.com发帖子）
