### ISSUE TITLE
erro import mongobd 

### ISSUE THREAD

**Issue by marcelowu** [fecshop/yii2_fecshop#25]
[nihaomodas.com.br@Umbler fecshop]$ ./yii mongodb-migrate  --interactive=0 --migrationPath=@fecshop/migrations/mongodb
Yii Migration Tool (based on Yii v2.0.13.1)

Exception 'yii\mongodb\Exception' with message 'No suitable servers found (`serverSelectionTryOnce` set): [Failed to resolve 'mongo_ghjfhjdgh']'

**Comment by fancyecommerce** [comment]
php-mongodb extensions

install mongodb 3.X

**Comment by fancyecommerce** [comment]
docker 镜像：http://www.fecshop.com/doc/fecshop-guide/develop/cn-1.0/guide-fecshop-about-docker-install.html
