### ISSUE TITLE
erro 403

### ISSUE THREAD

**Issue by wubuyun** [fecshop/yii2_fecshop#26]
安装后, 打开页面出现403 , 我没有设置redis, 可以不

**Comment by fancyecommerce** [comment]
严格按照安装文档操作

**Comment by wubuyun** [comment]
空间环境centOS  php 5.6 mysql 5.6 mongo 3.4, composer 更新后，倒入数据ok，
没有做 配置nginx，Redis的配置 ，Cache 和 Session 组件的配置，
就是打不开网页, 出现 403。。

**Comment by wubuyun** [comment]
Database Exception – yii\db\Exception
Failed to open redis DB connection (127.0.0.1:6379, database=6): 111 - Connection refused
Error Info: Connection refused

**Comment by fancyecommerce** [comment]
docker镜像：http://www.fecshop.com/doc/fecshop-guide/develop/cn-1.0/guide-fecshop-about-docker-install.html

**Comment by wubuyun** [comment]
需要密码，
@Umbler ~]$ uname -r
3.10.0-229.20.1.el7.x86_64
@Umbler ~]$ sudo curl -sSL https://get.daocloud.io/docker | sh
 password :
Sorry, try again.
