### ISSUE TITLE
安装后只有首页ok，按其他连接就Not Found The requested URL /men was not found on this server.

### ISSUE THREAD

**Issue by wubuyun** [fecshop/yii2_fecshop#27]
安装后只有首页ok，按其他连接就Not Found
The requested URL /men was not found on this server.

**Comment by wubuyun** [comment]
mongodb syntax error missing before statement

**Comment by wubuyun** [comment]
导入mongodb的表，数据，索引 ok
./yii mongodb-migrate  --interactive=0 --migrationPath=@fecshop/migrations/mongodb
就是导入测试数据失败.就差这一步了,

**Comment by fancyecommerce** [comment]
nginx设置去掉index.php，去论坛搜索，有帖子

**Comment by wubuyun** [comment]
我需要去ngnix.org下载安装吗，还是wampp已带这功能。

**Comment by MariaWf** [comment]
http://www.fecshop.com/topic/398

http://www.fecshop.com/topic/392

最容易的是使用docker compose 部署环境：
https://github.com/fecshop/yii2_fecshop_docker

**Comment by wubuyun** [comment]
ok 了, 在windows 系统不用nginx也可以的，fecshop\appfront\web文件夹下建立.htaccess并录入以下信息就ok了。
<IfModule mod_rewrite.c>  
RewriteEngine On  
RewriteCond %{REQUEST_FILENAME} !-d  
RewriteCond %{REQUEST_FILENAME} !-f  
RewriteRule ^(.*)$ index.php?/$1 [QSA,PT,L]  
</IfModule>

**Comment by fancyecommerce** [comment]
建议使用docker compose安装，半个小时搞定，大多数时间花费在下载库包上面：
https://github.com/fecshop/yii2_fecshop_docker
