### ISSUE TITLE
产品属性必须关联属性组才能进行设置这个比较麻烦，能单独针对商品进行配置吗

### ISSUE THREAD

**Issue by lincome** [fecshop/yii2_fecshop#28]
产品多且对应的属性也各不相同的情况下，每次都要配置一次属性组就显得麻烦了

**Comment by fancyecommerce** [comment]
那你想怎么解决？如果有，说出你的想法，如果没有就是发抱怨，抱怨完了，还没有说出来你对这个问题的想法。

看自己业务，如果没有特殊性，你可以设置一个属性组，这个属性组里面有你想要的所有属性，没有就留空，一个属性组就搞定了。

看自己业务具体来解决。
