### ISSUE TITLE
请问考虑增加 小程序入口吗?

### ISSUE THREAD

**Issue by itwarlock** [fecshop/yii2_fecshop#31]
### Additional info

| Q                | A
| ---------------- | ---
| Fecshop version  | 1.1.3.?
| PHP version      | 
| Operating system |

**Comment by fancyecommerce** [comment]
小程序可以使用appserver入口做后端数据api

小程序商城本人，需要自己开发了，这个目前还没有打算

被微信的公众号支付恶心了，需要企业资质才能申请开发，没有沙盒账户，对于个人根本无法开发，腾讯是反互联网的公司。

如果有小程序需求，自己开发吧，本人目前没有这个打算。

**Comment by fancyecommerce** [comment]
作为一个开发程序员，最厌烦的就是腾讯系。
