### ISSUE TITLE
/customer/address/remove api 缺少return

### ISSUE THREAD

**Issue by mistery-li** [fecshop/yii2_fecshop#32]
阅读源码时发现该api方法下面缺少return 响应

**Comment by fancyecommerce** [comment]
看不懂
http://www.fecshop.com/topic/624

**Comment by mistery-li** [comment]
很抱歉，因为是第一次弄这个，是我的错


我在github上clone的yii2_fecshop源码阅读的时候发现appserver\modules\controllers\AddressController.php文件发现actionRemove类方法缺少了return；



这个EditaccountController.php 我觉得应该加一个未登陆或者token过期的响应会不会更好 ？

2018-06-24 14:20 GMT+08:00 Terry <notifications@github.com>:

**Comment by mistery-li** [comment]
好像图片崩了，不好意思，我还是去论坛注册一个账号
