### ISSUE TITLE
Yii2 migratge方式导入表结构 mysql部分失败

### ISSUE THREAD

**Issue by nate-river** [fecshop/yii2_fecshop#33]
### What steps will reproduce the problem?
执行 ./yii migrate --interactive=0 --migrationPath=@fecshop/migrations/mysqldb

### What do you get instead?

/migrations/mysqldb/m170228_072156_fecshop_tables.php  186 行 应该；结尾

### Additional info

| Q                | A
| ---------------- | ---
| Fecshop version  | 1.1.3.?
| PHP version      | 
| Operating system |

**Comment by fancyecommerce** [comment]
发现这个问题了，因为从深圳回青岛，刚安稳下来，今晚才来得及处理，今晚发个版本
