### ISSUE TITLE
报告：方法的注释不准确的问题

### ISSUE THREAD

**Issue by spercent** [fecshop/yii2_fecshop#35]
### What steps will reproduce the problem?

查看源文件：

https://github.com/fecshop/yii2_fecshop/blob/master/services/AdminUser.php#L55

### What is the expected result?

关于 $username 的注释

### What do you get instead?

关于 $email 的注释

### Additional info

| Q                | A
| ---------------- | ---
| Fecshop version  | 1.4.6.4
| PHP version      | Any
| Operating system | Any

**Comment by fancyecommerce** [comment]
代码已经合并了
