### ISSUE TITLE
Report: 订单状态码拼写有误的问题

### ISSUE THREAD

**Issue by spercent** [fecshop/yii2_fecshop#36]
### What steps will reproduce the problem?

查看源码：

https://github.com/fecshop/yii2_fecshop/blob/master/app/appapi/modules/V1/controllers/OrderController.php#L131

### What is the expected result?

```php
$orderService->status_completed,
```

### What do you get instead?

```php
$orderService->status_complete,
```

### Additional info

| Q                | A
| ---------------- | ---
| Fecshop version  | 1.4.6.4
| PHP version      | Any
| Operating system | Any

**Comment by fancyecommerce** [comment]
这个没有问题，就是

```
$orderService->status_completed
```
