### ISSUE TITLE
CartController 中 getCartInfo() 方法参数有误

### ISSUE THREAD

**Issue by supercent** [fecshop/yii2_fecshop#41]
### What steps will reproduce the problem?
see the source code

https://github.com/fecshop/yii2_fecshop/blob/master/app/appserver/modules/Checkout/controllers/CartController.php#L27

### What is the expected result?

```php
$cart_info = $this->getCartInfo();
```
### What do you get instead?

```php
$cart_info = $this->getCartInfo(false);
```

### Additional info

| Q                | A
| ---------------- | ---
| Fecshop version  | 1.4.6.4
| PHP version      | Any
| Operating system | Any

**Comment by fancyecommerce** [comment]
提一下PR吧
