### ISSUE TITLE
关于 Code Style 的提议

### ISSUE THREAD

**Issue by successgdc** [fecshop/yii2_fecshop#43]
这不是一个 bug report，这是一个关于建立代码规范的建议。

我建议，遵循 [PSR1](https://www.php-fig.org/psr/psr-1/) [PSR2](https://www.php-fig.org/psr/psr-2/) 规范。然后基于此基础再制订其它规范。

如何写规则？

在项目里建一个 .php_cs.dist 文件。可参考 [这个](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/2.12/.php_cs.dist)。

如何使用工具进行检测和处理规范问题？

symfony 框架作者写的工具 [php-cs-fixer](http://cs.sensiolabs.org/)。

@fancyecommerce 有兴趣推动一下吗？

**Comment by zhao372716335** [comment]
不错，学习一下这个。

**Comment by successgdc** [comment]
@zhao372716335  让我们一起参与吧！

**Comment by zhao372716335** [comment]
@successgdc  大成兄，我先看看

**Comment by successgdc** [comment]
@zhao372716335  我跟作者聊过，他忙于很多其他项目，只要我们做了相关修改，他还是会积极合并的。

这个项目还是不错的，我们正在使用。但是代码风格不统一，二开不是很爽。不仅代码风格不统一，有些注释有文字错误，有些变量的英文拼写有误等等的问题。

**Comment by zhao372716335** [comment]
恩，可以修改，修改后发PR
您的项目发一下看看 @zhao372716335  @

**Comment by zhao372716335** [comment]
@successgdc  您的项目发一下看看
