### ISSUE TITLE
现在有多少网站已经开始使用了呢？

### ISSUE THREAD

**Issue by duanzhanling** [fecshop/yii2_fecshop#59]
现在有多少网站已经开始使用了呢？

**Comment by fancyecommerce** [comment]
无法统计具体数据，开源系统不嵌入后门

按照官网访问量和咨询问题的数目来看，保守估计50+

已知的案例：http://www.fecshop.com/topic/55#w3

**Comment by successgdc** [comment]
我司的商城，11.03 号已上线。

**Comment by zhao372716335** [comment]
这里有案例：http://www.fecshop.com/topic/55#w3

我们的商城，基于fecshop二开的，也快上线了
