### ISSUE TITLE
管理后台-所有列表，取消全选复选框后，全选功能失效

### ISSUE THREAD

**Issue by xuhuaiqu** [fecshop/yii2_fecshop#60]
管理后台-所有列表，取消全选复选框后，全选功能失效
![image](https://user-images.githubusercontent.com/11869986/48848929-36a46200-ede0-11e8-82d9-50af4cfc2b75.png)

**Comment by fancyecommerce** [comment]
已经修复，这个是jui的js bug

月底发布新版本，到时候更新fecshop即可。

**Comment by xuhuaiqu** [comment]
> 已经修复，这个是jui的js bug
> 
> 月底发布新版本，到时候更新fecshop即可。

能辛苦哥能贴下怎么修复的吗？项目在运行，比较急。

**Comment by fancyecommerce** [comment]
你可以重新刷下页面，然后就可以重新全选了，先这样凑合用吧
