### ISSUE TITLE
weapp implementation?

### ISSUE THREAD

**Issue by ace-han** [fecshop/yii2_fecshop#61]
Should we implement weapp client end? Since its becoming very popular in China

**Comment by fancyecommerce** [comment]
weapp ? like vue` or `react native`?  you can use `appserver`

demo:  http://demo.fancyecommerce.com/#/


Yes，Since its development in 2015, fecshop has become popular in China.

**Comment by ace-han** [comment]
I think I was not making myself clear. I meant should we get `weapp` implemented as a built-in client end? 
https://developers.weixin.qq.com/miniprogram/dev/

I think it will boost `fecshop` market share to a lot compared to other poor-documented eCommercial frameworks in China 😃
