### ISSUE TITLE
支持多商城吗

### ISSUE THREAD

**Issue by baijygo** [fecshop/yii2_fecshop#70]
### Additional info

| Q                | A
| ---------------- | ---
| Fecshop version  | 1.1.3.?
| PHP version      | 
| Operating system |
支持多商城吗

**Comment by fancyecommerce** [comment]
目前不支持，今年打算基于fecshop，做B2B2C类型的开源电商商城系统。

**Comment by fancyecommerce** [comment]
基于fecshop开发的多商户系统FecMall: https://github.com/fecmall

**Comment by fancyecommerce** [comment]
预计2019年7，8月份完成

**Comment by safly** [comment]
期待，有时间可以帮助开发

**Comment by materliu** [comment]
完结了吗

**Comment by shining228** [comment]
已经开发完成了吗？
