### ISSUE TITLE
autoload.php): failed to open stream

### ISSUE THREAD

**Issue by Aquarian-Age** [fecshop/yii2_fecshop#73]
### What steps will reproduce the problem?
10.1
### What is the expected result?

导入数据库

### What do you get instead?

./yii migrate --interactive=0 --migrationPath=@fecshop/migrations/mysqldb
PHP Warning:  require(/home/xuan/work/fecshop/vendor/autoload.php): failed to open stream: No such file or directory in /home/xuan/work/fecshop/yii on line 16
PHP Fatal error:  require(): Failed opening required '/home/xuan/work/fecshop/vendor/autoload.php' (include_path='.:/usr/share/php7:/usr/share/php7/PEAR') in /home/xuan/work/fecshop/yii on line 16

### Additional info

composer create-project fancyecommerce/fecshop-app-advanced  fecshop 1.7.2.0 -vvv
cd fecshop
proxychains4 composer update　-vvv
./init

php -v
PHP 7.2.5 (cli) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies

NAME="openSUSE Leap"
VERSION="15.0"
ID="opensuse-leap"
ID_LIKE="suse opensuse"
VERSION_ID="15.0"
PRETTY_NAME="openSUSE Leap 15.0"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:leap:15.0"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"

**Comment by fancyecommerce** [comment]
composer加载文件失败，导致下载的文件不全，请重新下载，注意安装教程操作的步骤是否有报错。
