### ISSUE TITLE
Found unrestricted file upload vulnerability

### ISSUE THREAD

**Issue by gsfish** [fecshop/yii2_fecshop#77]
### What steps will reproduce the problem?

Login the admin page and find a place to upload `.jpg` image. Intercept the request, change the file extension to `.php` and insert the content of webshell:

![](https://i.loli.net/2019/08/29/zT27v4RGrcDPwNS.png)

### What is the expected result?

The backend should deny for uploading unexpected file type (with .php extension) in `services/Image.php`, function `getUniqueImgNameInPath()`

https://github.com/fecshop/yii2_fecshop/blob/b15d7ed0f9ede3a75cbe971f10688567c5a95e9b/services/Image.php#L276

### What do you get instead?

The php webshell was successfully uploaded to the website:

![](https://i.loli.net/2019/08/29/WyJ1tRrK2VFYe8o.png)

![](https://i.loli.net/2019/08/29/lLmiwQEGk8r9fnc.png)

### Additional info

| Q                | A
| ---------------- | ---
| Fecshop version  | 2.1.6
| PHP version      | 7.1.13
| Operating system |Debian 8

**Comment by fancyecommerce** [comment]
1.有问题，请去论坛发帖：http://www.fecmall.com/topic

2.这个并不是bug，fecmall，对图片文件的检查，是通过php函数对二进制进行的检查，并不是通过文件后缀

3.详细参看fecmall论坛帖子：http://www.fecmall.com/topic/2169

**Comment by fancyecommerce** [comment]
您好，这个bug已经修复，请问怎么更新cnnvd：http://www.cnnvd.org.cn/web/xxk/ldxqById.tag?CNNVD=CNNVD-201910-197
