### ISSUE TITLE
什么时候考虑支持代理模式和代理平台？

### ISSUE THREAD

**Issue by zhanggaoxuan** [fecshop/yii2_fecshop#78]
### Additional info

| Q                | A
| ---------------- | ---
| Fecshop version  | 1.1.3.?
| PHP version      | 
| Operating system |

**Comment by fancyecommerce** [comment]
1.fecmall 的问题，一般在在官网论坛进行回复：http://www.fecmall.com/topic

2.不明白你说的代理模式和代理平台是什么意思，请详细描述一下，可以在论坛发个帖子
