### ISSUE TITLE
安装时候出现错误

### ISSUE THREAD

**Issue by micross** [fecshop/yii2_fecshop#80]
### What steps will reproduce the problem?

安装时候出现下面错误：

```
Notice: Undefined variable: argv in /var/www/fecmall/common/config/bootstrap.php on line 18

Fatal error: Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'fecmall.extensions' doesn't exist in /var/www/fecmall/vendor/yiisoft/yii2/db/Command.php:1290 Stack trace: #0 /var/www/fecmall/vendor/yiisoft/yii2/db/Command.php(1290): PDOStatement->execute() #1 /var/www/fecmall/vendor/yiisoft/yii2/db/Command.php(1158): yii\db\Command->internalExecute('SELECT * FROM ...') #2 /var/www/fecmall/vendor/yiisoft/yii2/db/Command.php(399): yii\db\Command->queryInternal('fetchAll', NULL) #3 /var/www/fecmall/common/config/bootstrap.php(34): yii\db\Command->queryAll() #4 /var/www/fecmall/appfront/web/index.php(25): require('/var/www/fecmal...') #5 {main} Next yii\db\Exception: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'fecmall.extensions' doesn't exist The SQL being executed was: SELECT * FROM extensions where status=1 AND installed_status=1 ORDER BY priority ASC in /var/www/fecmall/vendor/yiisoft/yii2/db/Schema.php:674 Stack trace: #0 /var/www/fecmall/vendor/yiisoft/yii2/db/Command.p in /var/www/fecmall/vendor/yiisoft/yii2/db/Schema.php on line 674
```

### Additional info

| Q                | A
| ---------------- | ---
| Fecshop version  | 2.3.4
| PHP version      |  7.2.19
| Operating system | ubuntu 19.04

**Comment by jpyeah** [comment]
我也出现这个问题,你怎么解决的?
This error also appears when I install, how do you solve it

**Comment by jpyeah** [comment]
已经解决,是nginx配置的问题
server {
    listen       80;
    server_name  appfront.fecshoptest.com;
    root  /www/web/develop/fecshop/appfront/web;
    server_tokens off;
    index index.php index.html index.htm;
    location ~ \.php$ {
        fastcgi_pass   127.0.0.1:9000;
        fastcgi_index  index.php;
        include fcgi.conf;
    }
    location ~ .php/ { ## Forward paths like /js/index.php/x.js to relevant handler
        rewrite ^(.*.php)/ $1 last;
    }
    location / {
        if (!-e $request_filename){
            rewrite . /index.php last;
        }
    }
    location /fr/ {
        index index.php;
        if (!-e $request_filename){
            rewrite . /fr/index.php last;
        }
    }
    location /cn/ {
        index index.php;
        if (!-e $request_filename){
            rewrite . /cn/index.php last;
        }
    }
    location ~ .*\.(gif|jpg|jpeg|png|bmp|swf)$ {
        expires      30d;
    }
    location ~ .*\.(js|css)?$ {
        expires      12h;
    }
}

**Comment by ywqyuan** [comment]
这个是报表不存，为什么改nginx 配置，我改了之后还是一样报错。
