### ISSUE TITLE
关于订单满多少免邮的设置

### ISSUE THREAD

**Issue by hama** [fecshop/yii2_fecshop#85]
大部分的电商应该都有这样的需求：
订单金额满多少免邮

现在的邮费设置好像还不支持？

**Comment by fancyecommerce** [comment]
不可能什么都支持，fecmall是作为一个基础电商框架设计的，是一个基层

fecmall应用市场来满足各方面的需求, 各种各样的需求做成独立的应用扩展：http://addons.fecmall.com/
