### ISSUE TITLE
Failed to open autoload.php

### ISSUE THREAD

**Issue by whiteLoveBlue** [fecshop/yii2_fecshop#86]
### What steps will reproduce the problem?
I install the fecmall2.4.7 by docker and i got this problem when I open the install.php website in my browser for installation.

### What is the expected result?
When I open the "appfront.xxx.com/install.php" website in my browser for installation, I get an error. Checking the nginx logs found that "autoload.php" could not be opened.
I also didn't find "vendor" in the git source file

### Additional info

| Q                | A
| ---------------- | ---
| Fecshop version  | 2.4.7
| Operating system |centos7

**Comment by fancyecommerce** [comment]
1.有问题，fecmall官网论坛发帖：http://www.fecmall.com/topic

2.安装文档: http://www.fecmall.com/doc/fecshop-guide/develop/cn-2.0/guide-fecshop-2-graphical-install.html

3.该报错参考：http://www.fecmall.com/topic/2267
