### ISSUE TITLE
Xss vulnerability

### ISSUE THREAD

**Issue by deenrookie** [fecshop/yii2_fecshop#87]
Hi, this is Xcheck team. Our code safety check tool **Xcheck** has found 2 xss vulnerabilities in this object. Here are the detail.

1. yii2_fecshop-master/app/appfront/theme/base/front/checkout/cart/index.php
line: 294.  `selectall = "<?= Yii::$app->request->get('selectall') ?>";` 
2. yii2_fecshop-master/app/apphtml5/theme/base/html5/checkout/cart/index.php
line:175  `selectall = "<?= Yii::$app->request->get('selectall') ?>";`

You can visit this url to verify. `http://fecshop.apphtml5.fancyecommerce.com/checkout/cart?selectall=xcheck%22;alert(1);a=%22`

**Comment by fancyecommerce** [comment]
bug fixed: https://github.com/fecshop/yii2_fecshop/commit/8fac6455882333cfe3d81c4121d523813e28e31a

thank you.
