### ISSUE TITLE
此处报错了，fecshop service method is not exit. fecshop\services\Customer::actionActionGetAvailableUserIdentityByEmail

### ISSUE THREAD

**Issue by cougar999** [fecshop/yii2_fecshop#89]
fecshop service method is not exit. fecshop\services\Customer::actionActionGetAvailableUserIdentityByEmail

https://github.com/fecshop/yii2_fecshop/blob/4ae4b011b0f7eed33906db889fd1f149a5f95d8c/services/Customer.php#L502

我改成了
`$one = $this->getAvailableUserIdentityByEmail($email);`

**Comment by fancyecommerce** [comment]
多谢，已经提交

https://github.com/fecshop/yii2_fecshop/commit/689344b6fbc96c6391ab959c317fff1dd83b553d
