### ISSUE TITLE
这里的”！“是全角字符，应该是”!“

### ISSUE THREAD

**Issue by imwc** [fecshop/yii2_fecshop#90]
https://github.com/fecshop/yii2_fecshop/blob/d681b25b249a19fa431df2fcd87f22aa399320b6/services/product/ProductMysqldb.php#L679

**Comment by fancyecommerce** [comment]
多谢提交，已经修正：https://github.com/fecshop/yii2_fecshop/commit/09a0ec26e69e778c66377c37413180ef666384fa
