### ISSUE TITLE
小程序登录bug：小程序发微信登录失败，错误信息code：110023 "message":"use wxCode to get user info fail"

### ISSUE THREAD

**Issue by EleTeam** [fecshop/yii2_fecshop#93]
这个问题是因为：小程序登录时用curl提交，但是curl没有禁用ssl验证导致的。 只需修改文件vendor/fancyecommerce/fec/helpers/CApi.php如下：

public static function getCurlData($url,$type="get",$data=array(),$timeout = 10){
	 //源代码不变

	 $ch = curl_init();
	 //设置选项，包括URL
	 curl_setopt($ch, CURLOPT_URL, "$url");

	//只需加入如下语句
	curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);//绕过ssl验证

	//源代码不变
}

**Comment by fancyecommerce** [comment]
这个不需要修改，用https一点问题也没有。

**Comment by fancyecommerce** [comment]
这个不需要修改，用https一点问题也没有。
